POST http://localhost:3333/videos
Content-Type: application/json


{
    "title": "Video01",
    "description": "descrição video",
    "duration": 180
}

###
//get all
GET http://localhost:3333/videos

###

//get with search
GET http://localhost:3333/videos?search=Video02

###

PUT http://localhost:3333/videos/05961fcc-ef14-4367-80c1-158fe171a0eb
Content-Type: application/json


{
    "title": "video2",
    "description": "descrição video",
    "duration": 180
}

###

DELETE http://localhost:3333/videos/05961fcc-ef14-4367-80c1-158fe171a0eb